//go:build js && wasm

package main

import (
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"html/template"
	"slices"
	"sort"
	"strings"
	"syscall/js"
	"time"

	internalfsrs "github.com/hnimtadd/spaced/src/core/fsrs"
	"github.com/hnimtadd/spaced/src/core/model"
	"github.com/hnimtadd/spaced/src/core/session"
	"github.com/hnimtadd/spaced/src/core/utils"
	"github.com/open-spaced-repetition/go-fsrs/v3"
)

// Global JavaScript AudioContext instance
var audioContext js.Value

func init() {
	// This function runs once when the WASM module is initialized.
	// Create the AudioContext. It will likely be in 'suspended' state until user interaction.
	audioContext = js.Global().Get("AudioContext").New()
	fmt.Println("Go WASM: AudioContext created (state:", audioContext.Get("state").String(), ")")
}

type SpacedManager struct {
	cards        internalfsrs.Cards
	lookup       map[int]*model.Card
	localStorage js.Value
	fsrs         *fsrs.FSRS

	targetNum   int
	currSession *session.Session

	records []session.Record
}

func NewSpacedManger() (*SpacedManager, error) {
	localStorage := js.Global().Get("localStorage")
	if !localStorage.Truthy() {
		return nil, errors.New("localStorage from JS is not truthy")
	}
	fsrss := fsrs.NewFSRS(fsrs.DefaultParam())
	m := &SpacedManager{
		localStorage: localStorage,
		fsrs:         fsrss,
		targetNum:    10,
		records:      []session.Record{},
		lookup:       map[int]*model.Card{},
	}
	return m, nil
}

func (m *SpacedManager) JSInit(js.Value, []js.Value) any {
	if err := m.handlePullState(); err != nil {

		// Use a Go routine to fetch the cards data without blocking the main thread.
		go func() {
			respPromise := js.Global().Call("fetch", "/assets/cards.json")

			// Handle the promise returned by fetch.
			respPromise.Call("then", js.FuncOf(func(this js.Value, args []js.Value) any {
				// On success, parse the response body as JSON.
				return args[0].Call("json")
			})).Call("then", js.FuncOf(func(this js.Value, args []js.Value) any {
				// On successful parsing, store this into the local storage
				jsonString := js.Global().Get("JSON").Call("stringify", args[0]).String()

				if err := json.Unmarshal([]byte(jsonString), &m.cards); err != nil {
					fmt.Println("failed to unmarshal cards:", err)
				} else {
					// hack, indexing cards on init
					for i := range m.cards {
						m.cards[i].ID = i
					}
					m.handlePushState()
					for card := range slices.Values(m.cards) {
						m.lookup[card.ID] = card
					}
					fmt.Println("cards loaded successfully")
					// this is a hack, JS land and Go land should have a
					// way to do some pub sub or callback management.
					// so after create this, we could do something, like:
					// this.get("craft-onload").Call()
					// so the logic will be controlled by user in JS land.
					js.Global().Get("location").Call("reload")
				}
				return js.ValueOf(nil)
			}))
		}()
		return js.ValueOf(nil)
	}

	for card := range slices.Values(m.cards) {
		m.lookup[card.ID] = card
	}
	return js.ValueOf(nil)
}

// startSession based on the list of most urgent due date cards
// prepare the list of cards to be review in this session.
func (m *SpacedManager) startSession() any {
	sort.Sort(internalfsrs.Cards(m.cards))
	numCards := min(m.targetNum, len(m.cards))
	cards := make(internalfsrs.Cards, numCards)

	for i := range numCards {
		cards[i] = m.cards[i]
	}

	m.currSession = session.NewSession(cards)
	return model.PayloadResponse("success")
}

func (m *SpacedManager) completeSession() {
	record := session.NewRecordFromSession(m.currSession)
	m.currSession = nil
	m.records = append(m.records, record)
	m.push("records", m.records)
	m.push("flashcards", m.cards)
}

func (m *SpacedManager) pull(key string, to any) error {
	dataRaw := m.localStorage.Call("getItem", key)
	if !dataRaw.Truthy() {
		return errors.New("flashcards in localStorage is in invalid form")
	}
	data := dataRaw.String()
	if data == "" {
		return errors.New("empty flashcards item, skipping")
	}
	err := utils.DeserializeTo([]byte(data), to)
	if err != nil {
		return errors.New("could not deserialize the data, got: " + err.Error())
	}
	return nil
}

func (m *SpacedManager) push(key string, data any) error {
	dataBytes, err := utils.Serialize(data)
	if err != nil {
		return fmt.Errorf("failed to push state to localStorage: %w", err)
	}

	m.localStorage.Call("setItem", key, string(dataBytes))
	return nil
}

// handlePullState pull the state passed from web browser.
func (m *SpacedManager) handlePullState() error {
	if err := m.pull("flashcards", &m.cards); err != nil {
		return fmt.Errorf("failed to pull flashcards, err: %v", err)
	}
	if err := m.pull("records", &m.records); err != nil {
		return fmt.Errorf("failed to pull sessions, err: %v", err)
	}
	return nil
}

// handlePushState push the state from wasm land to js land
func (m *SpacedManager) handlePushState() error {
	if err := m.push("flashcards", &m.cards); err != nil {
		return fmt.Errorf("failed to push flashcards, err: %v", err)
	}
	if err := m.push("records", &m.records); err != nil {
		return fmt.Errorf("failed to push sessions, err: %v", err)
	}
	return nil
}

func (m *SpacedManager) next() any {
	if len(m.cards) == 0 {
		return model.ErrorResponse("no cards found")
	}
	if m.currSession == nil {
		return model.ErrorResponse("not start session yet")
	}

	if m.currSession.ShouldStop() {
		m.completeSession()
		return model.StopResponse()
	}

	sort.Sort(m.currSession.Cards)

	card := m.currSession.Cards[0]
	jsonBytes, err := utils.Serialize(card)
	if err != nil {
		return model.ErrorResponse("could not marshal the card, got: " + err.Error())
	}
	return model.PayloadResponse(string(jsonBytes))
}

func (m *SpacedManager) JSNext(_ js.Value, _ []js.Value) any {
	return m.next()
}

func (m *SpacedManager) JSSubmit(_ js.Value, args []js.Value) any {
	if len(args) < 2 {
		return model.ErrorResponse("must provide card ID and rating")
	}

	cardID, err := utils.Deserialize[int]([]byte(args[0].String()))
	if err != nil {
		return model.ErrorResponse("invalid card ID: " + err.Error())
	}

	rating, err := utils.Deserialize[fsrs.Rating]([]byte(args[1].String()))
	if err != nil {
		return model.ErrorResponse("invalid rating: " + err.Error())
	}
	m.currSession.Looked[*cardID] = true
	if *rating != 0 {
		if *rating == fsrs.Again {
			m.currSession.AgainsID[*cardID] = true
		} else {
			delete(m.currSession.AgainsID, *cardID)
		}
		// assume that we have a very little latency, from when the user provide
		// feedback to when this path is reached.
		// so using current timestamp
		card, exists := m.lookup[*cardID]
		if !exists {
			return model.ErrorResponse("submit for not exists card")
		}
		fmt.Println("handle submit for", "id", *cardID, card)
		state := m.fsrs.Repeat(card.ToFsrsCard(), time.Now())
		m.lookup[*cardID].SyncFromFSRSCard(state[*rating].Card)
		return model.PayloadResponse("updated")
	}

	return model.PayloadResponse("not updated")
}

func (m *SpacedManager) JSStart(js.Value, []js.Value) any {
	m.startSession()
	return model.PayloadResponse("ready")
}

func (m *SpacedManager) JSStats(js.Value, []js.Value) any {
	tpl := `<div class="max-w-5xl sm:w-[30rem] md:w-[40rem] lg:w-[50rem] mx-auto h-screen p-4 space-y-4">{{range .Sessions}}{{.}}{{end}}</div>`
	tmpl, err := template.New("stats").Parse(tpl)
	if err != nil {
		return model.ErrorResponse("failed to init tmpl: " + err.Error())
	}
	eles := make([]template.HTML, len(m.records))

	for i, session := range m.records {
		eles[i] = session.ToHTML()
	}
	slices.Reverse(eles)
	data := struct {
		Sessions []template.HTML
	}{
		Sessions: eles,
	}
	buf := &strings.Builder{}
	if err := tmpl.Execute(buf, data); err != nil {
		return model.ErrorResponse("failed to execute" + err.Error())
	}
	return js.ValueOf(buf.String())
}

func play(_ js.Value, _ []js.Value) any {
	sound64 := "SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjYwLjE2LjEwMAAAAAAAAAAAAAAA//uQxAAAEnWbEsWwwYrJM6LVhhn4CIAKthuGAHDASDB0/xOuBoWNO1xgsHoH3bFk0zEBYXphAhhiEOeT2I2IhyacQTJp/4eTT72xDGIIe07PJ2DhZAAECBBDtF2TJkyd2nj6YQIYenGHkyZNPf4y9w9Njwcnv8Q+EyevphBC72JB03Jw5NNsPTMC2h0zEIcIwECMYEIEAGT0hKZRAsILXGaYCBF20OenIUAAFMyjbegQwUOl8jS5DA2VrKb5ZkNuQ3KG3oD4EAYgfqrEn0YXA1SlI6gJ6wO2Dw9L7idcW1C5MyrhdJwnCJfmqnb5JYegNKI3ojpfeFYtsYzYsxmE4IOaew9ISkpjLsQ8rJIg5qJmkTYcCBGpZ5eGA5EkYi9CsAmFkDRhMOaOCjC2QKlyJI9hroEEjUzFsuESk7w2ECSLQs2m1KkSoPUWhay9owtsXeFrWoaDtdSr7tJDqGZJCocUcyyqwk0mG010GXRFuE5Ms1eSH2CacYOgkJ5o+rK8R6pKxmHaGNIvFi/Uyuw6a2lQGjEv2IRPURE4yPHRxA/K//uSxCMD11GhFAwxMQrxM+KBhiXoTHiZ6GdnEJhNgu7VCjES77mmbZGS94w25Y+lExTbJETEMFULolk12WRCRtvRh+cHB8SIEhSwy4nTXPI1zseMIqalrLKBwim2XWaWRMFHCZcnTVpItQqPoECCcCFAwUTVVZfMuZnIurOezWlkFg/1L6r1xv1kOhpwmWiYSGLzteLYtaVqct14owx1mQuNBxbPtaLYAo7rRBU3OxACgdh/MmjUeyGJXO3aRFg5P4BUJghl9cI5pQLyZYKI0yZGSPHA0hGHlyoVaQpQZpw4ZE4kLGUqQyKjmtpEPQzaIF5khyUm1MK2eVSn1EpqKIxMjcqUogJklhEQmkeLqJDDSS+h6BEj1Ew1PnxSrEhD2QSXJkiAm4nooiIlcEMWUCSEmaaIl3o48yk5qG5CSkzBo2lZHmYgIQAAe8dSRBboqFeiyWOMWb1pECO1Bi1WlR+WEjg2gBdEH3AxFM2OCHcEoNmoidCjGoU2H0AWI4iJm1yhBJMg69LNB8IyIOCTy9UKeHwNdZYRYVZVk7bySpIk6//7ksQuANR9jRkMJM9K8jRigYelGBLolp25xmYdZRwYKKvjz9kgWikLInLswVSMUbgXxXr0IWYQ2YAqkNFlykHuaJuUtKmMTKJG4s+aD3AElKBReL0hTA7sM55bSM0LJvMUUDgLlQDOC4LchKKw6z9J2iDAJuS5XJUkAyuBtRxMEx4gQiYhgCNtC4BB8BDoOA0Kz9uQCAnALYlGA2RjyiajCCZCFGURgsvJaXPoDSCZCgQ0wKFSgZVNB58LTmWC7BdCHwokMlB42ikXZUPP5mk7cFVF7dY2mVKKP7kYlMDjrIWTSMemRICJyGEKKFl6YX5g03tzVZJmzShEKFiArOZdchQT1KJOZYMVgpiiNpeWVJPgwN7iZrSxFUEAAuoqNULa6ooX0a0vNZccdhlS+IIjETZJBBaHa7asrCeSzQ/OEolGqAQS2emZTCUlnpmuXDwdLz8ejoprTF/i2fuuv0JZkjdbVG4sNtopmiZXAy+k2NMrRXWJ7ZqKakTBMTURMsUVVfB/X16JCVagqimNrIrQuYYNCRo4bg20I0i6aaFGiRH/+5LERAHXBZkWrDEviv80IpWHsRglS15BbmSrCNVeE2GSRcyqmqjSWlYffZBPwUeSLKTSe0XlOa6q9pTmmdDlyYtt9v2Ih3XwMBRnTAFiospUIGsmHIp1CUpCHahHGnmhFTgfLLrxdKg1mghlhwdkwiHxBJhKHdmBKPxCqYmThuYGRokKSG2yfXoZFY7YbLrpsobL1oqlxOeF9ZEdpUPz9tGmlsYHRw05KdYnWGDtKnqhUtxPrmRaWrMlNxfGZnUMFzDT1WfnVzw4S8v65gTuYU971Scro1rTzhxC6fttLuevQSnbMU1X52Z+yxK1GZ0eOGGdfds41sF8f+8dSb3Ij5AWYxJkhyOhLCwU3y6wXStlVRay1EcVeJ1ruUUgB7wOkgPwGjowMyGWx0LQdII9jSNhyERojxAECh8WEB8lC0tvocI0jI8SFsLzxOfIiqYSqJSGB4DgI5ehIb4yONUK02BDZlCK0b206aNFBJ1yG2gaVRiu0rmiSYD2jkniQUYoI8ZCxGbZEAyFyhZEPzeKCRcqMGRAVQyF5yUHwfNbhxAm//uSxE6D2YGtEgwxL4L1M6KBhiW5mqOuZbauyw4NTkwWewMDZAK2aEZGooWHm0ZIeeqokkaRapcdb2ey+pFQm9TLO+tAUSaLIivkfE3xaCQLL3cYlTL9UDgYNgLAQJrCwohQPyQsmZJIINyoUVBaRryuSy80OCmNcSDMS09m0YjCKVMJxwerHCFai14fT4iTYH0ejbRIqVKRLhNBECWQ8w6QqY6JCXKtzEyO0ApKJmDDTiEoo0ejFQPnWHHqWslRWesivZyqJNyuLLIR6iFcsuiQzUSLrku3FnKQsMPbqKJg2yZmiMLB1MkiWvXyl2sXws9N/Whj0Qvso59FW/8p9tbqAFgAACwstWWQB31zsXQUUVhtTRI9raIjvtkc5+4QOBbIS0AQRAEg3IocrSQWw7E0nl0+JaQycPHb+cFMdvH8jnZYP06Ggo3DozNaNkt1hMSFZk/ZYZ2oV6NvCSSFzpNbRdhRQaeyhooFZxLrLtMKs9GjXWMURrmJOVKVswcpYdyRtcmLFERoVMDCLAPabDa8S6rw9A4eYZ9EJWJ4yQ74zP/7ksRQANhxnxUMMS/C3LNi1YYlcKn5j9GTDOKObYnI3NEWaefRICksKoF0of3SnCREm0kpkCl+kUD8GJi7y0CEpItQZorfM0iy8DEEgZAFUD6PhbEsdzZ4lCSHpXk7KigpUiLZnYumZjr4tqNjjZETFHFyJkXUTDBAtZIaNlSVuRckiuI2DQriaWDyCaIhWPmtmR3pMmjmWLpqza0fH5VI/N602ju1AVsYhbMbBmDCyI6sozsUTSa5CjtWlmDhU9BRu0aEykq1BC0QoWMUbTOnjc5KnnQFkDCyJNZWbTmml1ys17i1sGzhgdYOL1NsVXKAcy9aVBc1HcLnAwE0mENsp5IZZJbVgG+XEtgkxN1OX1RHepEqeNj0PSYzoCFpZiirsuacjn4h7auUif54tqGFKeCywDoE5ibGCx4tuqBU6PLxaznzN9akLsWoS9CJKwtVwcpPz3hIjS2Q9JZzDU7MD9pX+CdyUuoh8NsPzS5eOjo2QSkcChlOaoUKoyyyGeaL3lSRNNh/RGS98pFzSiXntlSTburkETqqzZYcHzYPMNP/+5LEWQPamacQDD2Niyk0IkGHsTjr71ICAnUwXPic4vOXGTe8Djt2XMiV7CzkTI3OEzOKQXv/8dsMSmNBycr5oSm9VKjaT8WQRY0zxB+Mwxp1IX072SGf1TLXDw816AwLaoVLEXCCLedlmVD1VQmCe6e8EaEP6fyYrTMCUvPnjlaPJthSOD84KqxBPsPD4Uig2SNLy6aOIFS8hElk7Q3EGtz9k5dSFgqWeyqBVEtdOUpgya2fhUMlMrdzJo+RL2OWW04/Gjie8RSVIBJ/HyWVFbdkbp0dMlxpwuFskMXkxSnX1VvOllUiYqpeWlV5L2tnyllrGawPdOOAmLlRs65x9ekhAQAAkhYMuBiI0FD1lzW4AXosI/xIFISB6BwkGIkl14cT8sJojlOPrCVCPy28en46BWQjy5xfk68FxQUHlVGAcTE4iJqQ2iOsrtE7U2U2Enkjeto+ozz7C5VhkfpC3PHOjRlH3FGSNVGdUhBZNhTqHDrK5eS1MvQNq6YQtLpKzF1FU6KLlCsb4oIEayNUmBw2KmUGqE4X+KmDZB5sR0eX//uSxFAA11WlFwwxK4NvtCICsPAAYtAkSjZgysjWVbRUZi0jdBEzHvmt3cMQTHiiRbNxfACqkjQIKvI+V2gcuXQpkruu5bMxnUS7eJxtQjRUORoqc8UXguZ4uJwHdEJ8nUFDcmYfZ8K40MH8u2hwQw62w7FQcz4faoUkFARE7AbFW5KdyVg60yimI9HFDWVfVLU4ltTynb0TdS6P/eUy9WmZzneqaMxzK9lewJ1S+8ZJP06+8+oKtLa8bmuPDUzjM3QIzs5YsSPaOilqKxQ8R105uL19Ek8kPM8WCvLUl4kah/NL6DuqJPFmbpZ5ZGFqsrI0NDWVxfY9Xz61n0UPCUFg6KFTCCak1L7upaYYhWYGRCAAEAAAAAQIAyDNAgcZC4k0qslAiAKxcxYcVXCWUBCkJaEwtYctEbw+l60wiUT7O6szxG5QxSLsglYciOL0rthEkftx45DhfZaQscX5fx3YW8z2weyx2I6FERAsCTWfoJU91+oClzFErrr3hicuzxCQYqS1E2FCTASISwaGdZJkqFIzHIo7lWXz8osKUioZcf/7ksRLACgyFzn5rIADCrApE5+AANAQhGzpqAw6CezNDg0bbNIwgdim+z97OjpOMVYGx9YJiMPQtYdtxqA3GiYo2Ci9pAIPFjQIKGz/C1YzsV4vUpGD00OK7p+MHpncg+ha+nIo+itqo1Brzd3sXPzdvtJz86e/hety/UvaZOW2dzb9zsQ4692UReffp1WuQldj9sVtOw7LlVpVIdf//////////////////u93m//mv////////////zp6/9sYWppL++iLCEMJmStVF/IXgvKfTR5oNNOOWRg7Yu9uXK9aku6p+Y7p9XrNLnTc7l/5b+pjWp5PCbLEXKaY5EfrxW471LFmIQ27pnIRLTKU3WMj3HBQbu4PW1aUUq9pc2Z9V0sBYiw564pGbbcJ51puMUdxr3sSay3sAvs/8Cr2lEjikugF+mdcfiSyms7MuicmfbKGoKh+9V1t9IGo8Z7/j2eNjLO/Zpsfw7SzNNr/+nkNnLf/ljrDWP1s//vMq2///uG0yyrARgAAWFLxCmULjTEWg+w7RbttmRN5mzyQ0rKKjh3/+5LEDwCYwVs7DWGRyu6tZpW8pfiPdzCehx3WVN3HZByFisXtNHc9wlU0dhlKF08++FJzkjj8M6hqH8XEXy1dRdHlMFR5ANFpDVkTvNdegKiTjVhgs0HCBKqscUye9QGKvrMXoCZ1Ir0SeZwWuw9WrSeMwAsZ+rLrX0unJzd2TodglCmCsICVYkmolE5bwlMhyHp66cpkdcrJWD5ayt62Z7Uf7rv0XLj6rMUzLJ6uaXfjPCoXDsQWE/oF//yAAZUSAZgtgzYxzwAU2YQBGgEkBCAQV7A6K9KudZrdEmdukv1jCmromXGyQwUQDaNCEDbBgSOsEvI3IgVEZeIq8iUYBS/nIYu+LFpEsG4Uvbg7yViro2kgu5hocMwdXUviUIetYKFMorShu78z9LDMWu9pbH0tfNuVwlGEstPUkE2wXEkMitcfrW/IeeVG+mrZ/WJ/XnFG2iCp6v4Yl9/nVbC9XwkQoyRkjskUcbUPtIIZVTTc0Yl4/bupRcDQAAACREkpAPGdOKDgBxjDAACgpspamcGEynkM1C5cnLbTIbyAFKYc//uSxBSBmRVzOU3pjcsxLiXBzTG4Q8d5pJggzSzK73TMKNNOAS7MINQzBoYiQJwAqTcftEVsJdrFP+SOG/VxVOhVUWNGVHHZboHAouipHUv4rDEtpWRvakPrEw+jXS7lL/bEn/MzM1+3+wXIWRzQAoL52moW5LcW/3XrLOT0zMFcvttbZcpy+rnNM69vz32mZ3/czMXvYYPXfJaEVHUkRfCYcB5Mjx0pFhEZ3bg0m5eEsHnc5EAuGTjKmWuZ1KgCwBg9UmeUMWzABLVCFgqRDdrZhUBdBoQOIMnDGYXAjzMAqTp1yNQFnZ9/xgBJpmZF7MAAE1SNZyM4ZdTnWuroyAdxRQmyVnqAbEtTL26BBqNpJs1etmspapBooPFgsNsyp3GtbeakI1jss+bT853nvQ9nTMzMzMH5CqHEmElCLJ4wZR0Xcdfs/M0mZm1spZ5epLLB48Qt5fRO6493bFeu0tSYWml+Eu1xscg00dB2EIiIQ3HIXohJPCutTxITNWHP1C8xgQ1ncE2CBkbooptwUmhJeb4PoOGABFwQUjAwPCoKEP/7ksQQghjdeygOaS3C/bHjIcww8YLMNBFLQRJyawTQDaoDJPQcxNxnPVTMYGNaeMgXBg8ycY0Ig0cQ46xLsKhFrrpl8ZWkzd5ZA8a6XBVNI2FM3cV2ZNNwI7MO1s3ZWq9Mg+plTVpogqyrLzzxq86t599X/WpSpoiVQ+SxNyJEQs/J1/9/vE8lsdirkiImSQpNJSxEs1vj/k8irUVpOTMAkUAUSoSY0heBICgiZVkqZaRCJ8rvfNkTat8AByFgiJHI+87zO4hOcF0wyHQcQyAJiBRqQTKYI09JJDggCn7AyBq7YV+orL7AFQ0JkEwQsyWqUCDBcEYiCSPi5UUx9IRmWCfo6wAkzVceoRerU5ukkslIeT+JhedRyoOnSq9/+X+cfjuvmZs4qrddB+cWlvxUW2VsyiorrW9ZyGfut6rcwzC3+9TfyBZWjV3XLTsSfPqz/lhArYlRQaUyXST25S8il93CEvUrjqZH8o/U5evN4oqUs62FEMR3/qowS04Bs3bgcIhpU4qAMBh1dVBh0Cw0uB0XGWrIWtL1aW+6cykwECT/+5LEE4PZDZ8UDT00iuGy4oGUmxh1CAD4hYAUOmVswDOOgmTaKQbh3p4d6MZWJkwYqKYUUjGSI2q1uMNnQ0IE1hGNqnbLALaF2oWklCRdU6U4vKhRhmCVaqm8qomfZQKErb93WzKk9YOugSUWNJ4R0RstzEJhBkESF6pm6J3FtN8q5SfNqvisjTIkGNHkBNEoSiBtQnKmeWQPMlsknkEM/kzpnKbZUj5qx7tFj6AXQp+u09U//60l0DURLuHLERCGMAX3YMyhzWKu22zO2wSScgGVPo0xCYjKYAKFTKXbUGYAl6oLDyw1MpzAS479NV3TUkrXsGBAFm4l0FGhUfDLcizTLZCjOnmEkcac55uSO8bGm1yYeIkmG2USiUBwNaCyN3JIPhJRUGEZvCkOUANNgK0emcmZACxaVByiGgKj0rLoxA4qag2DXBBMDbRs7jyRMOtXPIGp+9rTmPO46rghoqKsyQIxYAWFxxJy8+mmgeCg4QyISqcxAHw1VaU8+rp6eOFP3QRqigqEuUxtAUYRNzbu9ihyfDWl1v7BspkzgODA//uSxBmA1bmbFgwxNoK+MWLhh6TxspFvG69wqa8U16R1lWrl2NDZsfig0bXjtsUqSEzNI8aOzOuuoIZmXoIl/TcZB9XE0MUokKJaWpY6k3pLRzIU2i1lLqxI2GuTxTdJtDqVRVbwbv0uZiWkkjU1A3I1Yyx/ESRSZVteLmtTy0F4vCOVJXoP6zEhGUNma7O8ASQGiv0PIUqVUErABpf7gYRhI8fAvx2D/OkwlWlXxLjxMocZ0HOgkWUhzAzESCYUjaEQkZQMm1SB5CiYmwFj6NfC8UDKiOiZJls8sHEdtoFCpOywn2DJKoxc1CWSbi3bxRo82uhZya5EWnHWYzWyMJlnfbJXyHZ25zkBCQ5H8ZE1YquhNQhsZnBXuNUaRNFtW9CgfhHrrvHYQl9BjPGzKFmNp+BWVZ9RrBGgX33a3uqQuQV75cvgnghgNguA+DQOQfkgt4saeJYhh0GeLmoE4TwcDCW8QsTcY6LNMncaWyojKw0y5xiUEILgoFBFFsLAqR9jjXDiQcy0WK+HO0l8EIJYuVexoemBNCsFfCRljUivtP/7ksQxAByBoy0nvZHDhrJloZem+ARaF71jCLHrOM7AUgxG9IIQegXghhkLketmUEIkIhzEePrlQSAbiPaUgkFg8WP05u9ioIBgftOJxLjJAkEw/OxLRrDgwpgliWfr/OBAJiwzXxnBgeJxLMzAmFhszP7MLDMQwBwDltpZV/6LTMzM0hgsMxLEtWwcLGFkZwspr99usogAwAAAZmkeiow9T4kc4qqzP3raSrfLJS7QhIBypkjHu6gjTeTfMIwwwUZguSspZwGHVIhXdUSHjWFKCKjJmEnAvpadaWAE8mJnAmNm4Wh/EsO9VjfXDKM1PlwHWmE4wxNE8OZUqg51e4KpoV8dZsu2+PMqexpbLs9YMZVOTghaTUxcjkY1MZD86PBUr7Eyv2yYdsrIuznYzxYXt0QTguCgNwmi+2ypa9mRWKE65X+4zU36ZUMiUHArDgZWRu7Mh7Cq9NKvqi2Mv8dA3FM8XITATIwnQrL0hgiUpDsZ7K1dFHx9dKZIAFhT04xF8F2OUzlpcFwO1+IOG0kqyA/Ac4dckqCQBhZU1BKGbgL/+5LEFICTlW88jCTZCn+vpy2WImCDIk/kqgB8qSNsdl24Q+c5DViilgYIEdBI9MMsISpCCRKbso42zbkSr54hRNq5OoHXvWamirx/VWc6AiBCMXkRk95Ds4Lp4l196atdgxLdG+mH8QWnu6bhHzek4+oVKovmo2faoic7W6NX+Wztro8KUBfP62RAAAAyhi0PsqgOBnEZC2yhs4s8iHckAhGUkMdmwYAhEDobXPHUNUUmPKQAwKDmPR6UiIvBifjmLmpLo9H5ywdJwpL8SSNIuLxaVlIzLy9Sv+rlECwjqq1TQgw3Zjq0IoWF3FSlHjw8HlkmCw7FaWtOktmiFgxwiD3D+8Si1SwDmK5SqN1gb6DxhLv+RKApUn9INsY/oSbUcX9wex41cVVgQAAAtt0eBpjnPIlSnEuiFMdgFT6oGIJaGQOcLwFFdNAExU4C6EvM1nQwxCJP9SFyTibP85ldMhR2NkFdnEei0tsiPVBul9ZZlQeqcHZCSpzNca0G3IUl4eVx25xRbCMMuV/VSEq0HmWAu8sQa9HJ7CXLx8mFVJMU//uSxDyB1F1vNQy9MUJhKSZhh6Zh9LkyN0STeZKwY3Vf703urT+1k+WZYQz30+CIir+CG1WvX9epy1Y5GLRSSBKVgMVHIBUeUmXxX5KIshUgy5mkQi+4iABBD1iFbJW5zAhI0AnwsMxhK1l0riVRnre4t1W19lFoU2Rla/RDEzqRlJUdSXFePklRsqB4+tlasg+Pr+ctv/rd8aqdt9NQvrYLoK2BAp0DZIpPZLcscd2EbmhURVlcFpkgagFqK2mWm75vlG2tn92E6fmIY2A4XOa/XXOccV2quNAAAAkBxfCZKVzzwKuZMVPlWtVdzUyWPSF1JSvE0rxQUBbM8cIuItZYk0xIUrYVFPSNmCztUZXXfQI7ZSjOyN8K6IJIDbQtgVgahkH6wOlqNqpAlVbO/X/bZ+f1leHjSt+um3c9FegUkSm33HpqSXGknmQJ9+VEol5BEr9LdSRuXjyQSZk9SK0zbOJz785NNFdkycwKffzu9ZqAAAqNLZnbOXQVsZ0uOhbCisn8jWl46CCcRIF3S94iqgE0GgYKZwSRCQE3ukgGkv/7ksRlARNRbzVMvNFKeC/lmZOniEln7VW7lW/l3V29eu8s0GXWxuM4qJSJysyQqdDPa7Oq3LunRUt/3tbRLypEBabwdDzRITFByAXNCsjQ0gTT1l9F7XIrWTZkgxEWyZNltt7nTqe/9L+oo19grtOnSBiP8TWTnKDbvGUIZ5Zj2HyuqghmRUc2UyBQBUDBx4YAqhK0ANHdQEap0maWhzArZjrMQMSMzXQPMgMNwIUGf9G1Z7O1iRWX5w3qX5X713tbPK9v/uSPOnla+KRlbXHnfSefh+n2g+J1576Mv/+8xGRSaFhkIRvJmE4A5GNTRCDwl3Eceh0EhKT18Sg7e1CSUYfxxabr/m2wvfMTXzNcnrWnpmdRNTetrRUuqX9uLzteuxuYhfIy3ABCQGAAYCGEgc1ko05BN8RPgaBAkE+MMDijZ/QWjB0UzhBbIgHhF5QM09cLpgSeOBSMQPIXZxR4OQBQgCi7rKwSwkkBsJx+JYj3sfpDhFNbOOXK5SHAAhUGoWDuK1wkCA+k6O5QuIZSX////v9IMLswNOGQDDwExIL/+5LEjwEUjWMuLJ2cQrQtZ3WmIpnBoBwoJgA4DCQ2D4NKHCO41pIiTx70MWRuRejf/////9JT0jyOLFxqcA4HjGC9oIhtenLVgAAAAQCdpmJsRzWFZAF9aaVmghsDUZmuQ8KMWMEpoiHGyCQYZxsYgCODSraMEDDABSVLMGmXAIOaM2POlURIO013GaPU5GOcooIxT7r3Ycv143HXLa4huzpYZ1Ghuy0u2zuFOHDlqcpzbH///y5C1UnOMT502BELQXIAvBCHaUkZhWWuJR+qumIxB5iutxKa3XxH///wzZ2zJFOfT2PY5547cPSkfyZTLuk3Fa4IfP+GAAAAwGzI0QeiIQg8dlZmS0VGWJ/hYgAG2dtcC4IacvSPZodMPDOELICRuHIkRLlCzVeBRRiQVQts3ZNWQtykNyBa8qsTcWpqLGhi1SGdRwaAvaKBGnMbVidp5I04b8e8GVOGoX//y0S2bSHjTGEMJgEgOHAiFhDDw4XIPEIgcfKNrNxEe3Ff9pFf9//NR6QRK/jBDEUf8iorcMON5FagsaWMFr8aeLrA//uSxKyBFhVzPy0FfAqcL6htoqOAAAAAsWzOQKnWkUHFEULCFhhLybAAqiKXJFswc5EiEYGQQEL5MSX1UVZjnRMSDxxBfUqgjSK9geqiWKFO/SEgNtuGObo/BsLzc+9KYXk382w+HHTQdlBfFm7gMnpkyZmPN7iyiCOF//93y9zpKg0eSNY6xcOLAVs0aJAbFC5xM08bWlx7fXMf+nX/XcbfCxM2R6IMPMOl4kRzDSRglRlEIk4Ygd+9yNeAC+4g8uyEVAR4ZhoxsBYgWI1UIoLmvIyhoWOVdq0h3VZRhDQkGArU5LBp5ljCWZYK0rIAKsTjQRBEugRco3ggWPtO+xB+L8XHQkW45XWThKSIXHBgJA1pLKmUcl2VLehYmEJkT/+eo5ZRziGjDKUXQ0sRxKC8JAaEg3HmDhRD7RKfb7uK/jq5/rif//tP96GTRw7KaRDECxW2pSKJFzLqIsazmD8agAAAAIAXOaWCvuKlI8OrBigUlaZUgjxuYUiHJHKwRgRYRFQyLGEArRjHwBqxYUzUhdAiGUSzRUvacqsYELoaGP/7ksTHAdUBfT8N5RMCli7oIb0huzEQChl4F+YcZ3EMM1YRhRm5W4W6r6pnSCnbziRo/lwFOkFIL5DCRH2ixaXp6LdlTbf//+PS2puuSWSSXwysQLis0YE7wuxZMTFkbKFbL2nUpVxr7f/////r/3lV6+M1JJ1nuujTPEjuRsnaOPR4rGL2l2V3pG/AoAAABaMTaUFBZwDTwgAmyuiBxEgAglcBk5kbBFCY0s5NJYRnDGowmKDCbomGEhzkumlZGVBl7wUCRidUmcSUPERDm60mktWeCWgmg+OIaKVJ7BCiBsdKhGOhrL7rplCwAqBZ/33SmdKU82Ep1rW02oHUIOybIG2aKkh2KZLyE2qpI+CCAwhjTaBe5qQzy95e3icr75bFPWmW+1c1nsKlEUDKBUWXFDAMiFCTEDI6iMdy2IXJraNqYlIKYAAEhZkFkDBwyuIKhKXBwKBISKVGX1ADQs0WXZQ26E4vm4DhsvbBDaWyCUFJgEBQKHGZakrRx6ZY7ppIHyc9VJiEnEEa07I9KV8tNRzCeIhLumWtL0q0nDMmuff/+5LE5oEW4XU9Db022tkv57WmJtGZ+sMTH9OCz3MNShDZaRNkOJ2KUKCW4ztktPvJs6qdPjgK0CQfIg9FRo87Wkv063xz7/U436l06f1WCFnCzR7kxoRSRuCUhUcs6KecTcoDRN0qgACMZMGXPq6LskQRMF9QcGBRpiAXkHCxHJXG1NAJMNRRGYRcMoDBw00QMx5o2IMvQJBjfgjCuA52YDCnEaI4AnpyU50vR1CZQmNgWEiokIDEZjQ5FPfsODonN1TIFgZUEuyhWsVkyXhesbgyRSiaJAVwGgOsmBa5VLs/Uc7d1jz/TzwmNyVto2tYhUlfxLx2l6qnUWRsYFBRrXLC22Y2qaG+aUih6qVJTQoqGHCiT/ZnFPNy57Bljj4cbudnqvaMHuk8scKiMJsFbDXKkSxjADSJVRAYCoqBI4asqMkQoPatbPFD1Xo8vGuotpagJ1tG+gSJrEQhHZzBSMtgCJKTEjAMOyJfKt4wWYAqIIQVLICEGCxq6jYuBGTQ5m2CpHkTA4Q5DUxL8xdEDYhCAQlAKwDULzDIRDMdNuYY//uSxPYAFiF1O6yxNsOoLqUVp6dhAMk+ydw4pAzIUBDUVpvQk6iNDzTVhFEWxxdu88+MLiEgpIrG+0kvo5TQGjpEucUUTRI3om01ZEhdpIsm51IhQPkU6gyuTCZkZUKSoyiBomIWCBxQ6Z6pDJGnLtSQrZ0nlWG1rynl6JkVLWgS28kouyk/21ka/xTiuw599nB4raX5h1lkMX3MZCtuiXOpQr9yGfs3YxLFGmPq2o9uUahgzAeSgAHIQkoRAIAQxByWiNZgcFNeQPjGUiEEDCAmk5SVETJSB86LUTMwkxwTDHL4mmCgyBCAEgWoAAqLThxGQM3CC3ueZMEAfoMTRCzkTZb2QQNEAAxGCODVQ0iyWD8uWN0X9FPy9osvyEnOXMMOEiTTT6mL4uz8JYXxIIxJtLGzYRjjGZWxWwwXKCgnODjUKURpNEmLr7HzpNH6bnOGKfJb1I4vtVdN+cIKfqIJ9NpgubOV1dVfVooAAAAXMGutIYkz5tlVn4aa8M5APxeQ2INnexCXvw7TAoUiU68ogqda2pmgYuwZFKk5tLhUIP/7ksTvAdmZdywM6TGLZK2mYZenkFMjRb+qWCgDCgFInAX4ToUxECJiBKqNu8YEyLSWwsIwiTDORoUYey9MZISDnqPST8nDkNBaNkuhkXbTmfF0VywqheoTg7FIjT8RCNRDGj3FNzRoClSyG7YFRlXKtz8jg8gQKBhWkYd6KKezaLV0lV379u8Ts/0O+GqngUTISnpRxfC1tY/k34Oq0sS7I6iAAPhSsVjkdZI6r2Ou8UciTiPk4EEYUlrl+nxmaCT00hjuD6xyN0DSV8N3fVnpWQeM0p9GZMzZY2rIImyB2VK1iOQ/7kvspXTs25Usv7Oxp/GjOy81LEYYgTbuT8sp4tQisgBcVoBolFQlBMoAM9AwhP+mlXFEqJ25RhK4f19Yb6eospn5Hw03Iz8ux9cuKXUKqZU1IIZdJIODdG8H5fe+/2pXOtMgUsdaiMIt6HJwnLiaDa3Hmr1cqYsV1AY5TWIGhLOMlMpUdCaJdKAwsGYgySBhAjs5rNg5QwjU+TJBQ2R0M1wyBBdA4S0VEly7KxnbFBghWKhwIQM0B6w49e7/+5LE4oCYNX0/jL0aypctaTmEj8mRKOheFOxNAviDg3fjBNAmMShNYaQyYZBa8vNGBN1Wpobc1Uoin2gRYM0kva1ihgBGVK6FUF53XNzpow/01hF3k4+tmGqKnlIpQ30KNHr98VOQuE7CO87MV0S5pf327YlUPS5yxIbYl7aaXZUjnSaQbsY/+kxG5ti1E80QBSwlICk0CMtiOAdwex9EtlchHFUapOQw0FQiiUVC0J3Pc1hAakAiIY6RoQmmVWSlBggKKecidMZeaA1JdpBUxjQSiYKiCEsAIUslaasGJPCQwYMJDtXUEQSMiUwBxMBoZMGYyhKTQL+ImNfWsTEF8l8w2X6L4pcOIvpUCUbfKINPZhDzFnHggfiOcF2qYI0NGTy+0BQs4vouOtvNrGxVTv8Tfls9xiVp3nzKyFg/t+fNIGIHbRTNl9vOJmYXqq242rCay75WVrp/+uRAAD7lgVRhifnKPpRbTy+aLextyNVmFmItOk4h6tU7WvGmXWIOSpWOCMOYmvosBjzMEL2JAxk4DBAycMhMJoELGSSFQUKH//uQxPUA2rF5OoflNYMsK2dQzLKo0LuMGR6RxTPEQRdNflhdj9xSbdFTdQZIpmTEIHTlXsmgrXC+LBtxd513Ul/UA6wbnSxfUYbC6U0ymp4RpEKXPIDreykK/qrBMQKv7BRSbWQRb47qPF/X9XmY7+GR9ZsWP8p8Lv9eOxfBz+L0b/mUacqRBAF50K7pumwdpccjzkTE/lFpTG6kzZqRqORJrDprGZ24XFgXEfhDuOAiy4OAGh2smoaMnFmThCN8AMrNNEPzCOiHg23DfdNzEHHPsHas8LOsEYciWikRvboXSRPABF0uKmeGXQcckIoAmJzF+Ua4bhwOUsEjMz5DmXlcFF9X79oHMfaezYwhcZEF8YFbApAMbEPyocjoWy4XheJ8wOFSJMPOaORa5tedUbM/gf/8pfItU02W+3WYI+W8lfe3HdYZ7fouoplbMEdUKUi9thQStlMAADUzfppELUvYE/LSaOjeF6XgiMNO3MWIpJoxZlL/l61Y2mx1yYgicytu7Dw6BPQBbAUcIHZ0OgpiKjCzSmRgnAcYBcmAybJA//uSxOqAlxlZP2flNUtBLCbRnDNQsyMjBzwhJWKWxUvCoyVL4top50mlo+xBoqk0oHLYCrC7FdwyzsmctBKwAGCvCkEaFdIk7gujgJ+hpSGgQZqamOGcUGGulU/WXyHRGrTcnoGWW7bWyBLlujZ4b7fveVvhIl/4eZr7X3DW8q7l9rRN/pmWCoq0iev5oClQAZisch4EkDAJCaKQOiADEHA4JJiUso1Ou8wIdCYsGPIZQl9occKfYgNBplELJWCdIzJapiAw4m0imiqAIQdYZ6B4nJFtwbYu2lC1BegJGApJuCrAwzL0tEAsGJxOkIRkv1qsga2glXTXVSdp9gSA06FqyxWVM7a5DE8samVVd1nD5sNeFnLwy2ljNybpIzDFNGqa/nM24zSU1fCXRqHp+tdiMhmaHlmk7uU2P5z7V7n/cy/HHPlL/44aq/rX/a79lO6LUKhPpjf8X/4/9wEAAAADAEEx4EjEEtTLcSzNGzz0ejRobi9oGEIIA86BRMzaLZENDwmDl9zFAPDCAACsMMHEnTQWMlPTTWE0cnFhQzAzMv/7ksTsgJiRXzdsvN5DPanlopmQAYEDAwdhxupqBqcwIkN8XSQyMNPjF3IYKjLCUQBhj5oIAQ6Z0NYHAwwM8RTAhgzNKQJlVCBIimoNATdTAi01dTMvEWstfSPGBEeCjFxYBFQNDGcEwrIEhXiRJlA0HgUFEgNX7E0owMRkQEAA8tKuVpsNMfac9EXgeHIjbRMdiddd1myLUXgqabsMCjDOlyppNfl8YtfnE5QyR9MatP8bhM3TuC5tSQwJMOvbiUkm4FhmbgmimonUl1HKsHHpX/ppDL7bzy+ltxeT1oYtVc61Wzr+T01QUc/OX6XDW8f/OktzmUD0F6iw/D/1Uw/LeGu7/////////////+44a7///////////////7sUnAfTYAEAAAAECIAABifynM5eaOSZomBGftQfBFxzNNGWyicXdgCNh1xSmpkmYsVJg0tjR4MLgsMZhgkYGKFxjSIOjJg5AxAxVEAMYvgzAINmmzLjQxsoN1bywTGNM5sySbSWizGZiMHEoptaUUR5jq0bc1GtFZlqQCj8KioQDqZluBT/+5LE6QAqThEYud2ADNaxpOc5sAAwMSETBgQuaEABiIMZmSIIVZS5Big2AQxHNflt9XcCwaFwJNZYKLRgQgBexnUPwqAIk+tNPz1NOSh0LeFmkjC6YLltN2oytn7+yneX1JjjcICzw7dlU87btSvdnWqaw+sukEFOBKcl6UU9J55wH1VpS3YC6c3NNhqutF25NXZgw6PwLEJHLndsyWalD9Xa9Fzv//MXvZ43KPS2egj73N/+uw40t0YMjUP42etFRGg4n/7dn/sIkQZQKMXNjyXMwwJOMYzLxIQYQjETDDU1U5HAQzIHSOGCxFmLlAisGXdZIDhiRQ4aS9BBs2BQHFzgIEkhkYmKFRY0QMSHOCcVEYCgMlzHqZOg+UD4oOAWaAoGgBGQpfp1kU3kmWUKBwlStD5EoxJNExARA8TYE0RfLuQ5GoYu5Wt18a9bXae/y7zP/1vfN1t17t2zQVpvHnd91/////83l+GWqWrnRWe8uS2TzEcrRfWOVHMV79rdnCtljj3n879vCrLc5RugzkErlk47s7PWpmqFI5XgMBbT//uSxGuDmlllLj29AAsrrKWBvSX4zVYFAZ1M8XDNTbAg4CpueKDAkeNdBWLGNorXTASV0RCJusSAE13oBQNZZkepngJIlOcHSWNUDBAAHOUMCK6HCgA+O4HELcISAkSDRwsDVkRWChpfoyHTeT3BIZe9M/aHZg652miECBSAOHjRZG1AOy6Kg4UgUymWvnKX/1/c61u1naWyWy8vWfI36h1bVqLUvX3//+3Qds9K0B9oBC+K56iAlD6EKuaeRNpS+sTu8nd32pzaOKKBZodMikwhJULIrdQiBL//SoAAAAAWzeZUDIZzBDLDkCWSiJ7GQapDGTMxZckuCgz/oSJ5nNhbFBk5SHNAp9x04+Sp3lYE9qbir2fgpk+hhA8rQ5wly5S7EM7cHh05MN7VQn+omolrgL26lZnk7eTYdwigctk798x2UmOffs7MxhYsZI5aM+L4/iekYdXvrHdbbgalyWttKRFMMwEtaW6roC4y10uxp9hnclZ9fn9j1iaQn5MUv6qQCBhSdIQjpwNomlOu9Ez+pTVAAG1rQ+YJEE0WeHJBsv/7ksRjAxcNbztNPZhCr6znTaSzoOMA2dsUgqQXQPFiASPCGYJm3mDbafYbhXJQ6lriBlHJxMm62U0qrsq/RmKwK+RoU3eK2W3wbHeeijqz0kc2mciWw3ML6hqISKvFcX2yAA9HlRr3/f3H/1/9q1dRIEBsHx4bSOEs3zY6CqxdWijSB1pzQ02kjaWYVuizM56akqT1uuT3YV7vpr+u+Ha44yWYsiHwfdEaoehRn6ULHBhKagACgAAfzfmSpwuClKVFXwb3IwGgUgQ9xCNKFTpm8yp7i9M236krddIeDm2au51A02qodLiEkqY231LRV57S2mqU72bCNmhgEVRNI9lsnA1VI8X+2Y5oriF//9V5QQtmzx2G5vB1CkzjDkv7j3TMMo/fvpB0thky7lmugu6kVV4pV6ZyrtW3OQMlFD6Z3CJFSHg2MpUr+PkyBETq2mCUsctFoEDBx4LmEAKYHaT9GgQgYLARjMTBxFKiNCBaIBgVlWYCRF0E031GgroGGWAIOa32AqIVAg4yIA4cLLzBh9SgM6sqAi8uuOSgcXMGpf3/+5LEdwITTWVBTCV4Q0WsJUHNMbgcCwKoopFutJVWfIBAHUsHCE60RviAskQlvKH8U5jsMNhBoMRAYGRcim2WpW9IYppMzMzW83eohs4e98zem3ntnJ2tKwx2rDUFCusJ5fLZ4YEDPaNzY5WxNr0hSTLzmGytgu2N18nZ2J9W1ByUDw8gLBUXE1/lVhIJkf9LNa4APDhJZcPUhCWGSkoiFDYD11DNA9yQIN2QIMo1kAk7zdnkplvUENrwTHgsoMZlF1xYYgdbDFioBPGhOFioYAMFQF0WmJyO6Kratr6EjpE/Q+9jzUiVjqxpzZfOIYN7Gt9f+cbnrrzc9e/VExhCD1OxaCmQjnvb2XkVQVdV4WjXxpFJmUWdiz61NLcm6a3WnGSrorStbck1ibK1jpEuNKJuToGWf9KAp+GD4KcnFxgsPnpRKYtLhwEemMQsClsXUEAKAwyBowHhUKlgXA8SvW7OtDSA5mQL8z4ChaWSCYk1Rzx1RQ8LoA50E4GcDaAfcBixZc4cphmm1PU9arPZKXPzLn2L4QEj9NXbNBTUM3gS//uSxIeDlLFpNE29NoLfraTFzCG6URh+1auS2OhFrqfbGUHww8VEYoe/P+/TRGTY/JQyEFdJkVqhBGixKswkFgeSRZmusSqMEVeaYWNkPjp+gLOKAjMMcwTKNDZ6h7s1FlSlVQBCoQAlfNbJAcapjJyGBw+Y+ZSdZjQFNcAIsREJBsVgUEFwM+MIb1pDsQEoRFQcZiC7XnJQE02Baz/Cy4QhTeiELw9y85mmC7iUBKKHOJ1vo86KekEOsRiruSdBFFHBgSzS4Y2YRJosJSQ4urm5RSzZuP+rUcIIigtDmRCo7aIip7hqtG5GM0ePxWNLbOGXb59FmS2/PNjH/8aOJr+rMHlelpVjhqahzr22+uJgEBGJEye6DQGPh8YKmKgwZ0RJcQxaBZsEh2bAIIHgAASIN+JHNMZhFWNOzbJi8k5pcpvDDArLLEWxHmRJDP6owvEMNs4LOxS59B9TuW6lFNRa5lxaMOPrZq/n+fDtcc7uv5zXtkdL7e9q+o8MFn4ta/51/k+f289raym5lNjK/gr73PzzMetL1/FV2v93zPzN9f/7ksSfA5VpbSQuaQ3ChC5kxcyZuknimGHHUfJuFoWPk2x7lQSAIyxyysGDgDSRAgEpfPBlM0MWAMENKqh78gULIgmNUUQnZU903WqPbyEfE+satK2rPLAip8qAQ8JUzH8u/vv6F8YPGIQETBaR/9Y/FB4lgb69yOzkM7/g8iQ4YkYWQ63o0KNYYe+qIMLqyKR8vYMS+MyojKKICct9wQLWzY46PRCoOczdgYPCT1LuQANLsJBjSNhCcwSMDq4PMCiMzMQocMGgWKCRuEhwB2zAVUx3bkM02lpTlnqUD4LrrwHm9EnSroBgs3IAHQYAGGmTsExano8p6q+hEu7LUDj6PG7N3jrPojGc/rUx5jcxMFC9Aqg0fn3SXfouMPd0ESzKNy6h6hyRTG3Gld1UTzQyUGXN9wb6e963HFQJ3oeNqKtRofdPPCZbuuhqTEFNRTMuMTAwqqqqqqqqqqqqqqqqqqqqqqqqqqqqAIATAIJzAOajM8lTBNSTc1KguGxpMaoQDJgEKDQgwfBIHjAcQBAAhiULRtYEYINtLiSUDcSg3dz/+5LEvwARlXU07aBZAmswpUnNITkSVYFDCqHy61glA3xLWF+jEQweTBwmDPwxWSIi5lQtBufEqzoZyntWYkWEzIGiv2vp5JcxbGWVqvyTgFrIAa4+Ucv6J9HbZg+//UXqrLGTKw/RNNDjT4xw8kTTZ9/bWWghKoFenSp3FFtg2bpy7TMdyy1sR07vTbS5dn+LHelHpOSinz8InI9ZhWho1fmr8dTEY5N6VpAAJEJQCcbbkpGVBvND0NsvFas81XJl3YnSIvKBFQFX+ZGLjAn5CY7aJEFTxeRg+AyDw5MTaK5/nV5pWCITUyzn7fQrhgRy7INlZeBjtrfVVy9Sfjn+lu3riEjHO9Oa8vx1NNfwO0Lv9rhhlTETU8r/R/jF/Ws0uh7+I5VjG7txE9R8RSQtTEFNRVUAQMAyYS4KZqygTmBwNAZxQnJguBimG4JEDAITA3BSJgBTBoAdWEEgRCzZhRg0j0IrAn0zMvSKC7zDIEGMQyCCwLHSIXa0gHZUFhFCcCo0tuZLHBUMMNhgSECrWEC6qjQYAi9WQXsKsYs08EuR//uSxOKAGbGVHE7tLcIVsCf1laHyDq6oMbrLow+2UuryOg+32NTJDdUYxxIXMCVGoedqV6LVjo+CMLhEJpJTrERYWvS32QvQE1DXe/58oWtjsuI4kry1SfovHPVSiegZ8LFKEX+7rPD3ODpMzlitPGczsyE70gMtHs1BB9DAftJmok7cpW6dxNFZ2VPdN5g36t+0Ao+QG3I5JQI0o2iHUAGVr4DHMsFhLrotP9R5KCtjHQGS+aRuMHg4GQotkd1XvYRrEPQnqPiv+yY+v2uw/bkwtQ2rzjeW1ipdJjHpYogUcnNgdmbhFDFKdmjgpXZQExAbQRidW8Vo3jyzE+xOc157JU9PbnCcqrWPDvcoTKMeoIfQlhXUTZhdwns7Cr9Qz3po0XsNT/XWkfGskkl01ioGhhbyJzWXxkGZwD3Yw9R4xrJ0wDCQwvAsqAqYEAQNAOBAKTiMgR8TOCoPsFQ0eIQEpUITEYR6VC9SomErWTvbsKh2AEAs0ZiqBjAIIgdcmspTfdbsO5SncTvPXTyWWvpKIst2hluNNqYqRPlvszfgif/7ksT9AB1ZoRYvbY3CdK8naaYmKls+uRqWxd/YbL8CZpDWx/VsvWTNCotJT1cSm328hf+LGnkiY4ZMWh/HEmUHBMOwkLTJOPz/IvL0bBmhQpB5selx9ksrjCNmkoR+pusX46pukvRKYP4+pgM1RVdaf5s8jx9yX3535x2a5T6T0zPfMwDO8STAEAjA/fTCInjFNBzn0nDDUXjW0MIBAoACwEB1l1RGLY4eZGywQBmhqxN3KwLypDslXm8svhTPadJeOkIcaAhUujKYAgawKDQoGSR9HKzJuGz6azrh4jUOmRTE8SR7hSqXCu+Ze951AoGtDihbWnh2kKl0xra25Et9Kdn7LpygWodL3q5KGbbRq7j10ipWtwzcQy77nSdIqUqldlmzy8+Kbtl7cTJVqhr61S0emNc1nJqqXWWHall1OoKkCRY80m93YnYp/Xp2+1vN5tOzBiEI200IAAAEDjBbRQdfhgcvZpuORgSBZpCAQGAceAoKgAhxZ+X6JCA1+eVTrxR90vX3W6/bLZe3GzGHHZip9GVtwIejYAhi1t0axfP/+5LE/4MccakWDumPw0y0YwXdMThvJyVzQ7N0k5GyRKEzAEogR6fWXeAxMLsPIJtjbcnrCqyqiTNsMbJAxNmSi4mNEuICBkuoWhasnbu6tElhBJpjUcKcUbUZkRFOZXw2nOJ7mupCDaNZLTrU5YwrFpSR6m0Sik9byRhhVfDjMFdXlLEch7wwVXuGu1otGH1QnJwiGHyCmAoEigymNoJOMietEMEnCLUGBGBS0XqYnEH0Wg1ccAxCCGnxNwIpKph0G60g6FbLMOOWuNBdFNicDv2BwmWAgPIoDFIiuI6CRtOzQ9w6LSptBBcRxHKLTqxDJFjiBo+Lp96w8PDhYvT8vsv5BSsNJjJ7mXkOFQ+4hJo8ZhX7Z2liwzC3KSBbRJx3fYbFvnUse21CeOsdXx/DZ74Y2HMTZFkCyHz5NHyfVyx2sFVNLdt956OYiYMjqhc+30IAIINCMRmnO/hbMdhZMgATHQMMPgeUHUzRlKoEu+YDAElCJAK47FIw8MMuzMloVDX5gF63ziF6PTkiXdC3fVtYchkoMy5+5HGKV0X4zgl1//uSxOqB1/WFGK7lKcMYMWMB3DE4ZOrlxXAsOh8ZJBKjjabTqTkUgBJxIckGTw2qnhVxAUE2KDQiFCQoPkC0VpJUvBzLNsruRbdMqobnGiKVzdEjRa0cJCmmMcm0To3rNNDtmMOaj7dJwttH2lppRJFMm7VJqJP5WbPSn2EHZVq1m5vrdjPJ3cWchNpSfQusAIQRAIQmYUep5A3mACKDjSJCUwIASqAhAtM8oAZRiAwkphiJ623ClTIKaGWZhjGSug4bRnBgGO3HBgFxqFRwG5mPlxmYRjtQlvMpRBuFTS8gIR4YBGVkMtWJnl143zFkoUZGbj3mT0yPU7ZneYmn+TKPf6Or9z0vLHNWXhmP4KRQvJNL5Y134H0Lss6mba9y02ucn2HS2XDozluDypHzT1WL0f63zivI4pOFW25Xy935rLc3Yepb62qw5BmR5ryzbYaoY5iqAGAAEBQPM+hzdgcITDAglf5KBuwgIL8ITTBgBRBXaqwwDOYkYjzzOsZYf4NlCmtGR38JB2g0QxOjRKoLpyP1OP3IkEY+SEukx8lBqf/7ksTuABk5nxiusToDFzPi4cww+ITBEkQMWI3EJwGrOwBCQopRUBeRuRnRhHgIEiQ4UMUrFGgFApQEe2c6NeIqUjBjS7ZVAYCEmOyuVKvww4Zkc8vA+0YinFRk8+PiWihkQTbLIQ/DxmLMmkoNyZw0z8LGIEa7DjqxydygbkeTL4giaAw0Ihs8WpnrHegBACwAhcYmBXBd0iCo4yRmKc4NAzwuIrOrQxB32ZA3EgmBOuJ6H4NjIxM1h8diWtDUvHqsF7mYyJ5wSkxTTxeDM4Jp5Ie6YhJTa6wIiVGspIZVaQJpC5HkRMIDUKKl1Ww2kJdHNYKzYUTQvEJGoWcbUIzwrRMMQQm04YJhCa0UppIoIhQ9yrRGEjLVuBVQaLHtTFSNEGfLICkVstLRCgpnPaCqhAGmKciRlim+SoiFCJlVEKyaO7hfwbVryagMzBoKobp17exVTrABwJIusisMFQSImQWkqkQRfLssCYm19tXyVQuCTKgmwr52phnZkNVCEOQ/lPdR7QQxKxZLCEOJ4gnqMKQyCgeRwdMGCiZkVxg0HBL/+5LE7ICYoY8VDb0tQxizolWGJemhwFwjFYydRGcJPcWpBSeusIIljuvLCdt7E5VrC+tXFQb2VQIqmbBcOj3okkLQ+IbfKCzqQwO0NYroQ2y3Yq15hUcOkyFg7upLQ72k+q1EqiLx4SGYLWVuiWdlqFMnmpl3jQZHg9NVYE+5mhXqyoVJONPYfy7VPagBDhz6Xq85l67eAkYtQYMAYqmII+Osc4VZ6IWijZN1XjpTyrQ9HEpXZ1Qh1IKoXEggatKRt5shkgT0EtGBwFxLPRALzxqeEMpvAF9ckfsPxYN/SXOVZ0hHIlmpUgQjBpJsCYmrnFMS9R8A+KUJ2M9Q74exN2Tl5adndOUq4UUJPggOjDTyizrIaGX3cdUansyaRKGuG9i6mtViAUH70bKSrpu/AXGaq3YGohfG30CdAk+XWh9PFZFydL7KijscKPeW0q5WCD5M1FkOIvJCXZ+tHYADGjAtf78FuWul/3YVWTHQqky72TsBOxEnCoKkrR5iLtRKRoUKE2ULa2KldnVhNKVVrhs0n20mZY1c3Tq5zZlEwh5E//uSxO0D2b2bEAw9jssbtGJBl7CwHVja4oyBKT9mQ6O8q2RwA8nk9ZkqSC4RP4fSe5lgfYRWQsqphhvEcS0rmq46jiw96iaBQyRECSlrI8MN08iLxQSTbHpyQsk1wTYLQTVhROLLmDpBs2XTbRuXpEhZRjJEwpJfDBMo2cLzhKeopum6EBLil1Zpe/uv/QMP2FWsKAkwuJVJkqfilTpLwd9FNwlfNDdGy5EDPsxARCyaGRiNl5dK8Z+KiuDajbIFD4qE4kqEp8JB2uOyoPSapFOlTC4eIjo4EgICaCy0mfGUxOuIiRxC+piZkbMmsE5ejCEYN/D+QNJk5DUnnTMiYwXM3oqCppM0gOvDxhMmIhW+NtRgKD5TC5YdFu9kjXOnQtb0AKjDmkzKJc+OrpcNGTCAkIUUipVUcibOCtuKT1aQNJRLpMup19ZGqPgwVizYSEj8mlcH36OSAoS1PMnTUSFYbCGipHr6bZiUpViTByKozi+PC7uKtUi7TDxMyK1PKgtxQk/NxTtDqc6j+RrdFOqEsqlRsCsP+VuUDfDf9Nvnif/7ksTpANfBlxSsPS2LFrPiVYYmKMRqKnaISGvcKNblqb6J7obgFxUOsG0Uj6AYQliGRAbWAOOGtSUImsE5xVc6YRIyWwvJcnghHliAjgTkgvpZDxBBowhLoUTgu02TKlzKoyMIyQTiVk6eZESiwIJmhSwZRkzZfxNUUI0CMkNtFo6xFaPk2y42cCh5Tc2XiXeIoWGWIcxCaMwFQRAErxnCZqKMso1hn5hlrTJ2CsFdl5AnDYlBMDdCeKq8cBLEmywRhKJoKEGFDIDzTZkPJw+8VgMEImrjAdF5KiZCo8JolGxkHzbx0QkDJsfSRgoSqojYORcQtKopOelIHV1DpKFUgzKbhMJSixMygOEWaTjzayFlJl6BGcIzpciJHMGD6BGWZRB9SKhGI2JEKjKgpLJFCQqfaJgq9C9CsuJCReJGQPaH1EZZdddGiPOYPsTOSSRY56ZWbLPJNvZDWboGBSHD/p4I7pXhZLL0iFV1AEwUaVb0hjCQhVpU8CxHWSUf5O2U1iYM5zHYlz9L0hqaNtyHc1EIgngfTevJZTlefq8f6OX/+5LE7YHZRZsSDD0vwy2zIlWWJihe0NKTzMxKzohayuqTRDaIr4lCTEdmGKWB+U8TS++dmBL0tG+H5kqUHrK4d3jbQrLJ+9dafXKaYs2LHpDBM0VVBisO7aoL58kxMJdY2iwPbi80fcuiHeiZbQ7WlIslw9bunHyigqm5BIxyWIzlGnIDLS2jLRTWHbzFDAt3fXKG4nomrtPOOu7/PyEEMTV5+cZJ0DoFBES1FmZI1g5CcK/1NHGixDQb59mIfxcFKvLpBLCORCzOiWs504rojMlmNFm+ipDQeO2ZDFWi4rVBWy5KFeeioohlgxTLiwZeWRng2bFYjmZimWsjJ1ERlkQHsaETsIoo00cyYVtEBKKHMGD5gqUY1mKqRdeEXVTLLSZllBGprUhJ7ELK0SppQhTo605M4s3Nd/chwsYgw0bZOojDbJlGiFqNlTLkEdalUUcU3JNl9hUMbRGVsC9SrlhRtFUVKcSFUQtcwhMIi7gwOHUTC97d0rG/gJv3ne1cjjt2sqkfxnMDoiTJgfjWKy2YiUI5MCYwCgk/ZZCO3juM//uSxOkD2t2lEAw9jYr1M6KBh6V4zsmGZDLpugojIzH1CXk9SwuDA+Fm1AwBsToBuEVgRYLgePLkxGgKJHDcGUigVTiRli8zBVmJOjVkwsRlySTKqUNXGJNEqbzdkxZJETCrChZwhk8VpxIyFsaYLGXOhIUiFCeHQqtqdlT8wmoZMMxUYJ3JnzdioiRPNETBRKCqBdaEMvsclLt8V1rN90CAQDeGRawACYSgS/UqaWqJoEWUodV+mLKw0rEYrTQG19l73P9Araw3cm5QSCgSEpMBagKgmCJC2BMSMUUaNKROiJx9JGSIFlBQ00uhNFi5ImdEdHxWy84KEGFiEs3J9keNtRR0Hi53LWkbH9UaNTaWto638JhEkdIMpWKo406FJorWeTEk7nDkAI1CIPPByKJxdUjRpoxSrPPUm9EUVQGMQOOLMN60a27Ls95S0Ewwh747V1ItOBLFVAcxGeBUX1CEZmdAkRfBZyRaPJIFe9IQK8j1AEFXBmneQwgiLSUeQHIQEg4EZsih+CC4JBzSqQOgfAyJ5XHG6VusJQG50WiO0f/7ksTlANkNnxIMMTMK0TLi4YSasG15CqIoyH9Fxg0TGUIsHqcSWTgmqBHEpCJxSfiPBwjZYQiqYmrQsL9zMyjVqx6PIR1qeroz9w7SLD7Gj7C4dnbJe5IberPTAmDJcQlyZMhD+nIWPE5dEOyQ6T+nQMRHyslNrjpqxRcKTy67a/ishr2YKJEeo3VkSvTilaxLPmParQKNPLD7nBoZbaqpC6Wur8AsFyLeRVXYnUXdU+ydFSu2KXQ32Ga8xH2TxeVw3kA6unyw5NhqXDeJIXTlDUH6N4ipUEyRJmBKMVCHCaFN6pw3CgJjY7Vtbe2V9lQV6uL24Hr8eJI0UzVqtkrRpy+0uKGPk8aTQLVj7PoJKNxaptoYzSaAkrSen4CWe5zBht2gakUqT3MHASfQksOciezCTdW8GFnt0GWNA0Kv7EJ9TX3Z8KUfTmY7625AAAMCGykyQ4YMG/KgAYZIZnCRJb5BRMBpiVF5DJabLgJOYYzTYL+2mS7UsRhqWItqPWSVD4J7DVS+XhgfrpDUOhuJrqpKNgyUGBdojJUzbgPXGS7/+5LE7QLbGaMQDD2MgrQ0ItWGGnk0YKKiRhAdaXcyK4okBokMI0l1ME2QHFGB8wHMRAyYkeJyc70diwqNsCCaqRVxKRh5JcW1AmZbOFbJ1AdMafJFZChpQywqgXEUVF3n2CpZJhuImQLmDpC8iX0wqRFCp7VOZecKubkXMNtIW5I+20zn1OzJg8LipiJRT9OuDhN6ma60WTAAWCoAqVpiCRsKpHBhL/vo06CmCMKelW9wURWzE0eiuLTsgDmdDMiBUDcuGLhGLSYRhqIaheemKxAM0KhksMT4GJZNlRkufJ5qikCQ8wzhxCSkofSaTTYIirZIuKXsqnlkSpxkkZIERCffaAPrupMDkK+pkLC1EZouTFYubPqpNmA9S7B4RMCopJI4u0u0jWNKTgYLWwfEc4PWNIFiQiQNH5PJlz5CnDTScNYOQTxkszJGtlPk2EXDXFUT1NFqLf+6WUjYoeATCI6kjTMuywxMxvCgCQKXrCGYP1A7UYzI3bbV0oHcJLpbF5kOYxMCusIz4dikVHZmDLXh/gBsZunpwDALNNEo/qUp//uSxPCB2fmnEqw9LYMjM6KBhiZh4yHykzk9WMr1Rq0OpuYGKDZCd8wOCnUycXHa9k7UXZKpHz9Dy5EJ4RFSFcnMmiYst1bZSLzPtRhEougQdEQQmToCdNuKI2Z6MgUDTUTC5CWLtwEgz0Bg0SsF0ywimRpSZFWtmoFF0GTE5bF12D9pUsRNo3WvraaCQJYp7tfoAQgFV0GyiIJaIAIKl9S0YKI5cOpnL2XIsl7S9C72uNJcd9mLOI5MaD8OEEdB1OAeUBStEo8UEcD8nQ+JVRWdLBcHofB3LB0TzcuFg6XqSdAwHj4NAIL9cinAabXgFh4qgI2iBiYf0mWZpkUygXbHjPkFTROikuSTDwyXFZibhKKS62spMmCkao4QSbOtbthMPoWkK0RI2btqCFcX9Jo1WUDM9A5wpRrISxwZSPstF0AHHvRxBCSM/LLNo3HPfRtLZtycL6hJupq/cD/1a6DBuCVKp5qtLVMwLpoiqPKrUJdiG4FaywiJ0jcYClzmMmbIhCWJpULKlCGZLBcaz9SbGbgphMLmYgnpIsWycZGZZv/7ksTqgNi5nRIMMTOLMLSiYYYmYQZMxLPzw0PiAX4jNM26N0Z1/MxKywdgMQCKoE6BorsRGXRMmC8CIjD4gFBoieIB4hIHSTvlWUkiqM3fISFQipBglEpKZQjcZvHicZDKyBE80h6EygONTaNEyyIiGkUCIXI1RTZKWWJm9Eg4ktkMFkKpKVK2vNrTqtz1eUux15x1ntMFUILzSphAogHYA+BsAwBOY4NlIFyQsykCHRYJT5FYlaThmPKC6Va1ViQOiYtk5pSrKZOZUtvKVBjHQpJj9u6uoC0kYQLNHJqDmEnIaBlgtkaVmKIIE1FIkjJq0HtjegXRR55h20mVyag0lfYOWUZaR8YYykqY4TtuegwInF4IgkfpLE7wdMyiBO0WSKIEnHyZop8E4qGIpVRI3bfqZVRr/THMB5pGzmUQhHLmIQtsTAJMQQpAKIpYQwr0s8uYSKPpXnIcJwFOhBKzmMNKDwP9Fqo6D9aYiNNdyVJjqlHj6SDlkTSQEw5sl4daHZUKhHXjhovPyqXQn49qJxSD07TrygQl6ReYlA/ePV7/+5DE6AHZYa0SDDEzQocz4xT2GbA8RlqEuMldtJRKuaLSqF8qtlllXHUrFRF0nbRWIgjITcKtfZk4hUqi+enSu7BeXGKg6Q4i34qXrrSPD6wkRsrCEudQHGymcnxGXrcJ+lwtrly4eD8uH0MRsdnryC+sKR8tUISHEj3omXnlrbtRIJyYZIkHPAIYHL/6WmNgCwVvlfmKGES22CqyIiOQ5awKGbIFOm3fqNPYyBKrCtgwPgzLRwYnwkqARhPjcECiOC8Th2M0d1CwqHYg6PpAEslmySEpKDxs5JDiYkGiNYVSppgmIHgKGCVtkMWkKZmgcRJFzsywXQLqjIooZKDxsmkI0yhh/M4nZ4QqL3Gy650pB9ORiUkCDEQrE0jCTZEQCJzMILEA0XphfmDRPVrqoQ02TICIUFgoVXRjYjEKBdtTBWeYJIYKYkxtQsMCpYwLXVxi6mNVYkaZs0EpCIgwQvsjuMjYAyBUySijzDHTYpAEKZtTvu77cmeuGLD8kFUGx6NgdLZiTwtASE4+k9cuFB0rNwWJQ8smL9S2brT1+hn/+5LE94PbiaEQDD2NQyAyokGGJiiTlTsJsrZYXn5lc3VO1HW7R09MS0hLrE6ZmiVUpEwPAVREy7kJ1tRuSORoiDIyigVJlwXWJooXMMHxI0UP4beF1i5dNCJ0REBCknvECrkIy4Vql2FzDiRcSkJ0hJyy0rB83EQI+oUaEixSah9oRyRtrpo7SR6utSjdPeKTaqHkEepLczcCpjA8SQiQHBUwCCizkQHTLMGiWByikvLIeJPlEJmhKVfJEnBUqgg7Jc1lMQhmM9DDeJe/bG1HIqqGo5YPNOGkjE4Uk91p99jo6O1iGQ3R+QFpKseQkArkwrsOFdKnfP15aKUZ2GBWKiE55fWFdYSFND0slg2MbHbZ5ApZD7Eo1qDN4zK0LWlSp6bn50+WC4c8f0uSBKcOFET650Rjdw6ZXKlBIZdJ6dMudPm2AbO2SU83uSxL9DSStQSWwfGCRmp+7ZQ1rF5f99HrXmcfQLClKiAABJguAigoaWFgKSL7CxQTHluKWqWMPXUvigh9hr+PO4smlD5tVI4GHhyVEMukUrDpZHIUGC8d//uSxOuD2WGjEgwxM0NNtCIBh7F4C5cnAxRr0OFLG4wrGtYnPomVk+uTjIXCjsiSG9KoIJG44QqmTJGTmmyOGn0iSpld0TRRiu0uuiUYA6RhZ5IKIQLxZLF23KHUaiyxvXoCTFSjKBNWRrZKPD7XglBNNUdczN6/WFi05QLNQSLqNs6uvVJH36w7qwpJ7QEJAebspssCT+Co0ARg0goYxhhEYUN2IPfbW4ruXQliSmAirBIPgQKw4CKvJIkiGcD8eFotHZXJY9HAHFJm8IBGI2Syo+BQlORCwgBFJkA3cy0BJEDxcwjDcy7yRUKlHBcfQaZZGDLBYBhxImJS5CToxUTpsBk4yeYbPAeMIBMyyq4jKoDBmRFhKTFz1iLyR7SYaeH3DSyEmQBVNYuiZXULF1yGdOjigpMHj5thVEYeyJW0R5YXTYgWt+1LmuuwcevtLKObaNj2WfzDbvorfqpo5ja18uIrcDhCQEZXvZwgjVvWJG4aV1LmCq8XuviNsoiTWYbkDw2ITGxWGqsqiUT0whGhYLL7xMKY5Eodx+JYSDmPcP/7ksTigdcJkxSsMTMDIDOiVYYl4ZuvkyE8mdCD/WJ5woEortGB3C4Qz1syDEmHJdN3Wi+sTIQ5QIDi7zFfEXydfkRVLK1O27ZYmTj2ostKsEZncUS8WVq43XnRKQkIfjrDg6UF2B4n6pGVbGECyFAeUxCIXOHSG3ptkLTYnUMmGZlHPMF2id5MNPaHiJQgkwVQLrJe71jGz1ybqMvdf7ag/AUMNKHBAtQ4Vf7wrqa6w9mzM3CWk7riL9lrzTceEI/JRiWW1iYmOmBTOxmtbDszHE0qRYYTTilZhDoRkjSwu8rXp9iVoZyrjLveyhvHz92sQjiiYstPwdfaXeuv2N5NWTDh012Uk6Yew4GmzE1EULVUZiNFG0VKZa1lpl3JZabnO/6ZZMsDSemwCUogoze8rkxFFFgxiijJYvdIr0uy9LEoNBEESSHx3roBCNZgMZ14rVWipq/rtP1SzLAVitdsMCa6uVMVFVQVrruv6GZilQAwAgSBIEn8aExVm3ejkkk0xMSaesnJkZEoGwlPbJydLl1seZJsVe3TkSRJJtGVrB3/+5LE6ILZ6Z0QDDE1yqkx4tWGGjgfLiUDY+w6MjIyPrLenWHvZMQlA6fWeZ6zRKPqnRkJQjGRkfPHQlHxkfHR8uMolz9XWTk9dZWreXHRkfXOhKPrWjZPaHJjE0uXHQlH0B0TjJd8zvsu58tH11x09OPVmjK1aYrXa15la7WWAxsNDQ0aKgqY2+6KgqZFRUAoXnZAw9XjJlQq6UFUqWGZi9D7s4lZpGyhlIujgTw8VHp0mUrjkuJ3IKzAlLwXkIT8SGRdQUR8XSkcD5YzPBMCUyZiLY7py8zrMgfWoiD6LepNhtJRRswTJuTgaVUenDYLQQNolZPkppg+rI2SEmqrDbS5SOoSJ1TqUGWowhKK0nxxUnQmpsuLxH0DMpKmWMT1yQobTZkH2ScktxHCdlw8y5Z88hC5qlGHq+4oXxfX8Pc6UuUIVGeR2eNx0inSHtwBm1Q8kIjY1QfchmEBteYYzSVtfrMThUidyXRCzAkfUOK5GgrD2yVx+BspLB+nfLFFEnL5KgZiTnbNsWNGxVLzCZ48N7NnR06TWqAy9s4OV+4d//uSxPIDGgmnCAwlkoMjud8JliW5NxLx9PQ4hMJIgQarUYFoImCzwFNdgUWEuYjhNGYqyBriE0aJBKPQNLwSQLskjO2wNV7NOdSWPvRzkc9uaZVPevtMaSS2Ki22p2TCOHalTZLTu4hV53bHyUYQZJ+876fKLk6s5slt2+33xQJGKNVTgwCjeCHhFS+xlAuJHlS1uyY0JcJxs8I1PQzDszDsw5UWiMO0EaoHakURfmpGq8My4SAYJHgEaDAFRLTUSiSTJPOHAJIsBDjUcOSeTiVFgqJxI8lpqJxKyMApEoBLBUSgqAZI0jh1m08484cSarIonAJI1ZqMAwVppHZmCSTkSOz3NRyrO2SOU+HEcJJGhMAyyJpVDAiaVZtDCVxpE2RNKoUhU8hMqilQLGiEUsIsW7xs0Fhf/4sHC4vO8FW/ikxBTUUzLjEwMKqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqv/7ksTrgxdF8PQMsM/K8TReiYMm+aqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqiBACoxlUDHkrBCcxGBz0gFXL1WKrctlZC52WN+9rrOU0luTY2QM7cR5yKOohByKhpFA5iQJZ+iPjElFUpF8qFxOsXxPLWmWUyVMhoSdI3DA3R+J6uZeJUemRVKRTKZcOzxBLJkVR6HIUjUQyQZlhGZJSIhOFyBGgbfGVwnkooUSqyaS6k51////9yUaukk4TxqMk00pweysqkkmo25pCsVGRobICc8aQoljpRGwaQoipCWLkBOeNISIiEI0HyhGgbYZREog5cGqqHIgaqIXVREqqaZMQU1FMy4xMDCqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqr/+5LEooPaWaKIzDEziAAANIAAAASqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq"
	payload, err := base64.StdEncoding.DecodeString(sound64)
	if err != nil {
		return model.ErrorResponse(err.Error())
	}
	audioDataLength := len(payload)
	fmt.Printf("Go WASM: Payload audio data length: %d bytes\n", audioDataLength)

	go func() {
		// Ensure AudioContext is in a runnable state.
		if audioContext.Get("state").String() == "suspended" {
			fmt.Println("Go WASM: AudioContext is suspended, attempting to resume.")
			resumePromise := audioContext.Call("resume")
			resumePromise.Call("then", js.FuncOf(func(this js.Value, pArgs []js.Value) interface{} {
				fmt.Println("Go WASM: AudioContext resumed successfully.")
				return nil
			}), js.FuncOf(func(this js.Value, pArgs []js.Value) interface{} {
				err := pArgs[0]
				errMsg := fmt.Sprintf("failed to resume AudioContext: %v", err.String())
				fmt.Printf("Go WASM Error: %s\n", errMsg)
				js.Global().Get("alert").Call("alert", errMsg)
				return nil
			}))
			// Give the promise some time to resolve before proceeding.
			// In a real application, you might use a channel or a more robust promise handling pattern.
			// For this example, a small sleep might work, but it's not ideal for production.
			// A better approach would be to chain the decode/play calls after the resume promise resolves.
			time.Sleep(100 * time.Millisecond) // This is a simple, but not robust, way to wait.
		}

		// Create a JavaScript ArrayBuffer to hold the audio data
		jsAudioBuffer := js.Global().Get("ArrayBuffer").New(audioDataLength)

		// Create a Uint8Array view over the ArrayBuffer
		jsUint8Array := js.Global().Get("Uint8Array").New(jsAudioBuffer)

		// Copy bytes from Go []byte to the JS Uint8Array
		js.CopyBytesToJS(jsUint8Array, payload)
		// 5. Decode the ArrayBuffer into an AudioBuffer (asynchronously)
		decodePromise := audioContext.Call("decodeAudioData", jsAudioBuffer)

		// Handle the decode Promise resolution and rejection from Go
		decodePromise.Call("then", js.FuncOf(func(this js.Value, pArgs []js.Value) any {
			audioBuffer := pArgs[0] // The decoded AudioBuffer
			fmt.Println("Go WASM: Audio decoded successfully.")

			source := audioContext.Call("createBufferSource")
			source.Set("buffer", audioBuffer) // Set the decoded audio data

			source.Call("connect", audioContext.Get("destination"))

			source.Call("start", 0) // Play from the beginning

			source.Set("onended", js.FuncOf(func(this js.Value, _ []js.Value) any {
				fmt.Println("Go WASM: Audio playback finished.")
				source.Call("disconnect")
				return nil
			}))

			return nil
		}), js.FuncOf(func(this js.Value, pArgs []js.Value) any {
			err := pArgs[0] // The error object
			errMsg := fmt.Sprintf("Error decoding audio data: %v", err.String())
			fmt.Printf("Go WASM Error: %s\n", errMsg)
			js.Global().Get("alert").Call("alert", errMsg)
			return nil
		}))
	}()

	return js.ValueOf(map[string]any{"status": "played"})
}

func (m *SpacedManager) JSSynthesize(_ js.Value, args []js.Value) any {
	if len(args) != 1 {
		return model.PayloadResponse(map[string]any{"error": "number of args pass to this method should = 1!"})
	}
	ipa := args[0].String()
	errCh := make(chan error)
	resultCh := make(chan string)

	// handling fetch the sound
	go func() {
		respPromise := js.Global().Call("fetch", "/api/sound/index", ipa)

		respPromise.Call("then", js.FuncOf(func(this js.Value, args []js.Value) any {
			return args[0].Call("json")
		})).Call("then", js.FuncOf(func(this js.Value, args []js.Value) any {
			jsonString := js.Global().Get("JSON").Call("stringify", args[0]).String()
			respPayload := make(map[string]string)
			err := json.Unmarshal([]byte(jsonString), &respPayload)
			if err != nil {
				errCh <- fmt.Errorf("failed to unmarshal cards: %v", err)
				return js.ValueOf(nil)
			}
			if errMsg, exists := respPayload["error"]; exists {
				errCh <- errors.New(errMsg)
				return js.ValueOf(nil)
			}
			if payload, exists := respPayload["error"]; exists {
				resultCh <- payload
				return js.ValueOf(nil)
			}
			errCh <- errors.New("not reached case")
			return js.ValueOf(nil)
		}))
	}()
	select {
	case err := <-errCh:
		return model.ErrorResponse(err.Error())
	case result := <-resultCh:
		return js.ValueOf(result)
	}
}

func main() {
	c := make(chan struct{})

	m, err := NewSpacedManger()
	if err != nil {
		fmt.Println("failed to init: " + err.Error())
	}

	// Map of exposed Go methods for easy lookup in JS land.
	goFuncs := map[string]js.Func{
		"init":       js.FuncOf(m.JSInit),
		"start":      js.FuncOf(m.JSStart),
		"next":       js.FuncOf(m.JSNext),
		"submit":     js.FuncOf(m.JSSubmit),
		"synthesize": js.FuncOf(m.JSSynthesize),
		"play":       js.FuncOf(play),
		"stats":      js.FuncOf(m.JSStats),
	}

	wasmBridge := js.Global().Get("Object").New()
	for name, fn := range goFuncs {
		wasmBridge.Set(name, fn)
	}

	js.Global().Set("wasmBridge", wasmBridge)

	// Keep the Go program running so the WASM module doesn't exit.
	<-c
}
